name: React CI/CD with Docker and Azure

on:
  push:
    branches:
      - feat/*
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: ##security report upload p[ermission
        actions: read
        contents: read
        security-events: write

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run CodeQL Security Scan
        uses: github/codeql-action/init@v3
        with:
          languages: javascript,typescript

      - name: Perform CodeQL Scan
        uses: github/codeql-action/analyze@v3

      - name: Build React App
        run: yarn build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Download Build Artifacts
          uses: actions/download-artifact@v4
          with:
            name: react-build
            path: build/

        - name: Log in to Azure Container Registry
          uses: docker/login-action@v3
          with:
            registry: allappsregistry.azurecr.io # global DNS unique domain name for Azure Container Registry unique identifier ip
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build Docker Image
          run: |
            docker build -t allappsregistry.azurecr.io/countdown-app:latest .
        - name: Push Docker Image to ACR
          run: |
            docker push allappsregistry.azurecr.io/countdown-app:latest

  deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to Azure Container Instances
          run: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az container create \
              --resource-group AllApps-rs \
              --name my-container \
              --image allappsregistry.azurecr.io/countdown-app:latest \
              --registry-login-server allappsregistry.azurecr.io \
              --registry-username ${{ secrets.AZURE_CLIENT_ID }} \
              --registry-password ${{ secrets.AZURE_CLIENT_SECRET }} \
              --dns-name-label myapp-container \
              --ports 80 \
              --os-type Linux \
              --cpu 1 \
              --memory 1

        - name: Deploy to Azure Web App
          run: |
            # Deploy to Azure Web App
            az webapp create \
              --resource-group AllApps-rs \
              --plan countdownServicePlan  \
              --name testingcountdown \
              --deployment-container-image-name allappsregistry.azurecr.io/countdown-app:latest
               
            az webapp config container set \
              --name testingcountdown \
              --resource-group AllApps-rs \
              --docker-custom-image-name allappsregistry.azurecr.io/countdown-app:latest \
              --docker-registry-server-url https://allappsregistry.azurecr.io \
              --docker-registry-server-user ${{ secrets.AZURE_CLIENT_ID }} \
              --docker-registry-server-password ${{ secrets.AZURE_CLIENT_SECRET }}
            